import type { Category, Transaction, Rule, Import, MonthlyAnalytics } from "../types";

export const CATEGORIES: Category[] = [
  { id: "groceries", name: "Groceries", icon: "🛒", color: "#10B981" },
  { id: "dining", name: "Dining", icon: "🍽️", color: "#F59E0B" },
  { id: "transport", name: "Transport", icon: "🚗", color: "#3B82F6" },
  { id: "shopping", name: "Shopping", icon: "🛍️", color: "#8B5CF6" },
  { id: "entertainment", name: "Entertainment", icon: "🎬", color: "#EC4899" },
  { id: "utilities", name: "Utilities", icon: "⚡", color: "#6B7280" },
  { id: "health", name: "Health", icon: "💊", color: "#EF4444" },
  { id: "coffee", name: "Coffee", icon: "☕", color: "#92400E" },
  { id: "income", name: "Income", icon: "💵", color: "#14B8A6" },
  { id: "uncategorized", name: "Uncategorized", icon: "❓", color: "#9CA3AF" },
];

export const TRANSACTIONS: Transaction[] = [
  {
    id: "tx1",
    accountId: "acc1",
    amount: -4850,
    currency: "CAD",
    postedAt: "2026-02-21",
    description: "LOBLAWS #1042",
    merchantNormalized: "LOBLAWS",
    categoryId: "groceries",
    manualOverride: false,
    notes: null,
    tags: [],
    explainability: { reason: "rule_match", ruleName: "Loblaws → Groceries", matchType: "contains", matchedValue: "LOBLAWS", confidence: 1.0 },
  },
  {
    id: "tx2",
    accountId: "acc1",
    amount: -1850,
    currency: "CAD",
    postedAt: "2026-02-20",
    description: "STARBUCKS #9021",
    merchantNormalized: "STARBUCKS",
    categoryId: "coffee",
    manualOverride: true,
    notes: "Morning meeting coffee",
    tags: ["work"],
    explainability: { reason: "manual", confidence: 1.0 },
  },
  {
    id: "tx3",
    accountId: "acc1",
    amount: -7200,
    currency: "CAD",
    postedAt: "2026-02-19",
    description: "UBER EATS ORDER",
    merchantNormalized: "UBER EATS",
    categoryId: "dining",
    manualOverride: false,
    notes: null,
    tags: [],
    explainability: { reason: "rule_match", ruleName: "Uber Eats → Dining", matchType: "contains", matchedValue: "UBER EATS", confidence: 0.9 },
  },
  {
    id: "tx4",
    accountId: "acc1",
    amount: 285000,
    currency: "CAD",
    postedAt: "2026-02-15",
    description: "PAYROLL DEPOSIT",
    merchantNormalized: "PAYROLL",
    categoryId: "income",
    manualOverride: false,
    notes: null,
    tags: [],
    explainability: { reason: "rule_match", ruleName: "Payroll → Income", matchType: "exact", matchedValue: "PAYROLL", confidence: 1.0 },
  },
  {
    id: "tx5",
    accountId: "acc1",
    amount: -12499,
    currency: "CAD",
    postedAt: "2026-02-14",
    description: "AMAZON.CA MARKETPLACE",
    merchantNormalized: "AMAZON",
    categoryId: "shopping",
    manualOverride: false,
    notes: null,
    tags: [],
    explainability: { reason: "rule_match", ruleName: "Amazon → Shopping", matchType: "contains", matchedValue: "AMAZON", confidence: 0.8 },
  },
  {
    id: "tx6",
    accountId: "acc1",
    amount: -9500,
    currency: "CAD",
    postedAt: "2026-02-13",
    description: "NETFLIX.COM",
    merchantNormalized: "NETFLIX",
    categoryId: "entertainment",
    manualOverride: false,
    notes: null,
    tags: ["subscription"],
    explainability: { reason: "rule_match", ruleName: "Netflix → Entertainment", matchType: "exact", matchedValue: "NETFLIX", confidence: 1.0 },
  },
  {
    id: "tx7",
    accountId: "acc1",
    amount: -5500,
    currency: "CAD",
    postedAt: "2026-02-12",
    description: "PRESTO CARD RELOAD",
    merchantNormalized: "PRESTO",
    categoryId: "transport",
    manualOverride: false,
    notes: null,
    tags: [],
    explainability: { reason: "rule_match", ruleName: "Presto → Transport", matchType: "contains", matchedValue: "PRESTO", confidence: 0.85 },
  },
  {
    id: "tx8",
    accountId: "acc1",
    amount: -3200,
    currency: "CAD",
    postedAt: "2026-02-10",
    description: "SHOPPERS DRUG MART",
    merchantNormalized: "SHOPPERS",
    categoryId: null,
    manualOverride: false,
    notes: null,
    tags: [],
    explainability: { reason: "no_match", confidence: 0 },
  },
  {
    id: "tx9",
    accountId: "acc1",
    amount: -22000,
    currency: "CAD",
    postedAt: "2026-02-08",
    description: "HYDRO ONE BILL",
    merchantNormalized: "HYDRO ONE",
    categoryId: "utilities",
    manualOverride: false,
    notes: null,
    tags: [],
    explainability: { reason: "rule_match", ruleName: "Hydro One → Utilities", matchType: "contains", matchedValue: "HYDRO ONE", confidence: 1.0 },
  },
  {
    id: "tx10",
    accountId: "acc1",
    amount: -6750,
    currency: "CAD",
    postedAt: "2026-02-07",
    description: "FRESHCO SUPERSTORE",
    merchantNormalized: "FRESHCO",
    categoryId: "groceries",
    manualOverride: false,
    notes: null,
    tags: [],
    explainability: { reason: "rule_match", ruleName: "Freshco → Groceries", matchType: "contains", matchedValue: "FRESHCO", confidence: 0.9 },
  },
];

export const RULES: Rule[] = [
  { id: "r1", name: "Loblaws → Groceries", enabled: true, priority: 500, conditions: { merchantContains: "LOBLAWS" }, action: { categoryId: "groceries" }, matchCount: 23, source: "user" },
  { id: "r2", name: "Amazon → Shopping", enabled: true, priority: 500, conditions: { merchantContains: "AMAZON" }, action: { categoryId: "shopping" }, matchCount: 17, source: "user" },
  { id: "r3", name: "Uber Eats → Dining", enabled: true, priority: 500, conditions: { merchantContains: "UBER EATS" }, action: { categoryId: "dining" }, matchCount: 11, source: "suggestion" },
  { id: "r4", name: "Netflix → Entertainment", enabled: true, priority: 700, conditions: { merchantExact: "NETFLIX" }, action: { categoryId: "entertainment" }, matchCount: 8, source: "user" },
  { id: "r5", name: "Payroll → Income", enabled: true, priority: 900, conditions: { merchantExact: "PAYROLL" }, action: { categoryId: "income" }, matchCount: 6, source: "system" },
  { id: "r6", name: "Freshco → Groceries", enabled: true, priority: 500, conditions: { merchantContains: "FRESHCO" }, action: { categoryId: "groceries" }, matchCount: 4, source: "suggestion" },
  { id: "r7", name: "Hydro One → Utilities", enabled: false, priority: 600, conditions: { merchantContains: "HYDRO ONE" }, action: { categoryId: "utilities" }, matchCount: 2, source: "user" },
];

export const IMPORTS: Import[] = [
  { id: "imp1", fileName: "td_visa_jan2026.csv", status: "completed", totalRows: 47, importedCount: 46, errorCount: 1, createdAt: "2026-02-01" },
  { id: "imp2", fileName: "td_chequing_jan2026.csv", status: "completed", totalRows: 23, importedCount: 23, errorCount: 0, createdAt: "2026-01-31" },
  { id: "imp3", fileName: "td_visa_feb2026.csv", status: "processing", totalRows: 31, importedCount: 0, errorCount: 0, createdAt: "2026-02-21" },
];

export const MONTHLY_ANALYTICS: MonthlyAnalytics = {
  month: "2026-02",
  totalSpend: 67349,
  totalIncome: 285000,
  transactionCount: 9,
  vsLastMonth: -8.3,
  byCategory: [
    { categoryId: "groceries", amount: 11600, percentage: 27.4 },
    { categoryId: "utilities", amount: 22000, percentage: 22.0 },
    { categoryId: "shopping", amount: 12499, percentage: 18.6 },
    { categoryId: "dining", amount: 7200, percentage: 10.7 },
    { categoryId: "entertainment", amount: 9500, percentage: 9.5 },
    { categoryId: "transport", amount: 5500, percentage: 8.2 },
    { categoryId: "coffee", amount: 1850, percentage: 2.8 },
    { categoryId: "uncategorized", amount: 3200, percentage: 0.8 },
  ],
  topMerchants: [
    { name: "HYDRO ONE", amount: 22000, count: 1 },
    { name: "AMAZON", amount: 12499, count: 1 },
    { name: "NETFLIX", amount: 9500, count: 1 },
    { name: "UBER EATS", amount: 7200, count: 1 },
    { name: "FRESHCO", amount: 6750, count: 1 },
  ],
};
